DELETE FROM volunteers;
DELETE FROM volunteer_slots;
DELETE FROM concession_events;
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-08-31', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-08-31';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-08-31';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-08-31';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-08-31';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-01', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-01';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-01';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-01';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-01';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-03', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-03';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-03';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-03';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-03';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-08', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-08';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-08';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-08';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-08';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-10', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-10';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-10';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-10';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-10';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-14', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-14';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-14';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-14';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-14';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-15', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-15';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-15';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-15';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-15';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-17', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-17';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-17';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-17';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-17';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-21', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-21';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-21';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-21';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-21';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-22', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-22';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-22';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-22';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-22';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-24', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-24';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-24';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-24';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-24';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-28', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-28';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-28';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-28';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-28';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-09-29', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-09-29';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-09-29';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-09-29';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-09-29';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-01', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-01';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-01';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-01';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-01';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-05', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-05';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-05';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-05';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-05';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-06', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-06';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-06';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-06';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-06';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-08', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-08';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-08';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-08';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-08';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-12', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-12';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-12';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-12';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-12';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-13', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-13';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-13';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-13';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-13';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-15', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-15';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-15';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-15';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-15';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-19', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-19';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-19';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-19';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-19';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-20', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-20';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-20';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-20';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-20';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-22', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-22';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-22';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-22';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-22';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-26', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-26';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-26';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-26';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-26';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-27', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-27';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-27';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-27';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-27';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-10-29', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-10-29';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-10-29';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-10-29';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-10-29';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-11-02', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-11-02';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-11-02';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-11-02';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-11-02';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-11-03', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-11-03';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-11-03';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-11-03';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-11-03';
INSERT INTO concession_events (eventDate, season, location, isActive) VALUES ('2026-11-05', '2026', 'Hoya Field Concession Stand', 1);
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'co_cook', 0, 1 FROM concession_events WHERE eventDate = '2026-11-05';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'kitchen_assistant', 0, 1 FROM concession_events WHERE eventDate = '2026-11-05';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 0, 1 FROM concession_events WHERE eventDate = '2026-11-05';
INSERT INTO volunteer_slots (eventId, role, slotIndex, isOpen) SELECT id, 'cashier', 1, 1 FROM concession_events WHERE eventDate = '2026-11-05';
